services:
  db:
    image: postgres:16
    container_name: keystone-db
    environment:
      POSTGRES_DB: keystone
      POSTGRES_USER: keystone
      POSTGRES_PASSWORD: keystone
    ports:
      - "5432:5432"
    volumes:
      - keystone-db-data:/var/lib/postgresql/data

volumes:
  keystone-db-data:
