-- KEYSTONE V1: initial schema. Mirrors the JPA entities in com.zidio.keystone.domain.
-- Seed users/customers/sites/parts/work orders are inserted at startup by DataSeeder
-- (passwords are BCrypt-hashed in code, so they are not stored as SQL here).

CREATE TABLE customers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(200) NOT NULL,
    contact_email  VARCHAR(200),
    contact_phone  VARCHAR(50),
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE sites (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT       NOT NULL REFERENCES customers (id),
    name         VARCHAR(200) NOT NULL,
    address      VARCHAR(300),
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_sites_customer ON sites (customer_id);

CREATE TABLE users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(150) NOT NULL,
    email                   VARCHAR(200) NOT NULL UNIQUE,
    password_hash           VARCHAR(200) NOT NULL,
    role                    VARCHAR(20)  NOT NULL
                            CHECK (role IN ('ADMIN','DISPATCHER','TECHNICIAN','MANAGER','CUSTOMER')),
    customer_id             BIGINT REFERENCES customers (id),
    reset_token             VARCHAR(100) UNIQUE,
    reset_token_expires_at  TIMESTAMP(6) WITH TIME ZONE,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_customer ON users (customer_id);

CREATE TABLE parts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150)  NOT NULL,
    sku         VARCHAR(50)   NOT NULL UNIQUE,
    unit_cost   NUMERIC(10,2) NOT NULL,
    stock_qty   INTEGER       NOT NULL CHECK (stock_qty >= 0)   -- stock can never go negative
);

CREATE TABLE work_orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(30)  NOT NULL UNIQUE,
    title         VARCHAR(200) NOT NULL,
    description   TEXT,
    priority      VARCHAR(10)  NOT NULL CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    status        VARCHAR(20)  NOT NULL
                  CHECK (status IN ('NEW','ASSIGNED','IN_PROGRESS','ON_HOLD','COMPLETED','CLOSED','CANCELLED')),
    customer_id   BIGINT       NOT NULL REFERENCES customers (id),
    site_id       BIGINT       NOT NULL REFERENCES sites (id),
    assigned_to   BIGINT       REFERENCES users (id),
    created_by    BIGINT       REFERENCES users (id),
    sla_due_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at  TIMESTAMP(6) WITH TIME ZONE,
    closed_at     TIMESTAMP(6) WITH TIME ZONE,
    sla_breached  BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_wo_status      ON work_orders (status);
CREATE INDEX idx_wo_customer    ON work_orders (customer_id);
CREATE INDEX idx_wo_site        ON work_orders (site_id);
CREATE INDEX idx_wo_assigned_to ON work_orders (assigned_to);
CREATE INDEX idx_wo_sla_due_at  ON work_orders (sla_due_at);

-- Append-only audit trail: one row per status change (never updated or deleted by the app).
CREATE TABLE work_order_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id  BIGINT       NOT NULL REFERENCES work_orders (id),
    from_status    VARCHAR(20),
    to_status      VARCHAR(20)  NOT NULL,
    changed_by     BIGINT       REFERENCES users (id),
    changed_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    note           VARCHAR(500)
);
CREATE INDEX idx_wosh_work_order ON work_order_status_history (work_order_id);

CREATE TABLE part_usage (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id  BIGINT       NOT NULL REFERENCES work_orders (id),
    part_id        BIGINT       NOT NULL REFERENCES parts (id),
    qty_used       INTEGER      NOT NULL CHECK (qty_used > 0),
    logged_by      BIGINT       REFERENCES users (id),
    logged_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_part_usage_wo ON part_usage (work_order_id);

CREATE TABLE time_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id  BIGINT       NOT NULL REFERENCES work_orders (id),
    technician_id  BIGINT       NOT NULL REFERENCES users (id),
    minutes        INTEGER      NOT NULL CHECK (minutes > 0),
    note           VARCHAR(500),
    logged_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_time_logs_wo ON time_logs (work_order_id);
